### ISSUE TITLE
And perhaps vice versa?

### ISSUE THREAD

**Issue by MrMadSpin** [13xforever/wgs-exporter#1]
need from steam in game pass
example starfield from steam to gamepass version.

**Comment by 13xforever** [comment]
Xbox save data api is completely software defined, you'll have to reverse and reimplement how data is organized for each game, and I'm not doing it lol

**Comment by MrMadSpin** [comment]
me for pc

**Comment by MrMadSpin** [comment]
thanks issue resolved https://github.com/HarukaMa/starfield-xgp-import/releases
